name: to_do_list
description: A new Flutter project.
ublish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

## Slidy Scripts 
vars: 
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts: 
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.0
  flutter_slidable: ^0.6.0
  animations: ^2.0.0
  ripple_backdrop_animate_route: ^1.0.0
  dartz: ^0.10.0-nullsafety.1
  animate_icons: ^2.0.0
  dropdown_search: ^0.5.0 
  flutter_staggered_animations: ^1.0.0 
  path_provider: ^2.0.1 
  flash: ^1.5.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  animate_do: ^2.0.0
  animated_text_kit: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.1.1
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  easy_localization: ^3.0.0
  flutter_zoom_drawer: ^2.0.2+1
  intl: ^0.17.0
  wave: ^0.2.0
  location: ^4.1.1
  map_launcher: ^2.0.0
  responsive_builder: ^0.4.1
  rx_notifier: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0-nullsafety.2
  flutter_modular_test: ^1.0.0
  build_runner: ^1.12.2
flutter:
  uses-material-design: true


  #Referencia dos arquivos externos
  assets:
    - assets/avatar.png
    - assets/images/
    - resources/langs/